
export const translations = {
  en: {
    nav: {
      main: 'Main',
      privacy: 'Privacy Policy',
      terms: 'Terms & Conditions',
      download: 'Download App',
      slogan: 'Your journey, our priority'
    },
    hero: {
      badge: 'Now Available in all Saudi cities',
      title: 'The Trust of Our',
      titleHighlight: 'Customers',
      titleEnd: 'Built Us.',
      desc: 'Safe, reliable, and premium transportation services at your fingertips. Discover why Sama is the choice for millions across the Kingdom.',
      btnPrimary: 'Book a Ride Now',
      btnSecondary: 'Explore Services'
    },
    services: {
      title: 'Our Specialized Services',
      s1: { title: 'Passenger Ride', desc: 'Premium point-to-point transportation with professional drivers.', label: 'PASSENGER' },
      s2: { title: 'Sama for Her', desc: 'Exclusive female drivers for the comfort and privacy of our female passengers.', label: 'SAMA FOR HER' },
      s3: { title: 'Quick Delivery', desc: 'Reliable parcel and order delivery across the city in minutes.', label: 'DELIVERY' }
    },
    about: {
      title: 'Our Story',
      desc: 'From a local initiative in Sakaka to a nationwide leader in transportation. Sama Taxi\'s journey is a testament to quality and trust.',
      quote: '"Our customers\' trust is our creation."',
      arabicQuote: 'ثقة عملائنا هي من رفعت اسمنا',
      timeline: [
        { year: '2017', event: 'Launch in Sakaka', desc: 'The application starts its first operations in the city of Sakaka.' },
        { year: '2018', event: 'Expansion', desc: 'Sama broadens its reach to serve more residents and travelers.' },
        { year: '2020', event: 'New Ownership', desc: 'Strategic acquisition to enhance services and operational scope.' },
        { year: '2021', event: 'Major Expansion', desc: 'Launch in Riyadh, Eastern, and Western regions.' },
        { year: '2022', event: 'Growth', desc: 'Organizing massive rewards and competitions for our loyal users.' },
        { year: '2024', event: 'Nationwide', desc: 'Expanding to cover most cities in the Kingdom with MG3 2024 fleet.' }
      ]
    },
    privacy: {
      title: 'Privacy Policy',
      effective: 'Last Updated: 10/02/2026',
      sec1Title: '',
      sec1Content: '',
      safetyTitle: '',
      safetyContent: '',
      sec2Title: '',
      sec2Content: '',
      sec3Title: '',
      sec3Content: '',
      fullText: `United Sama Transportation Services Company is committed to protecting your privacy. This Privacy Policy explains how the Company collects, uses, and discloses your personal information.
This Privacy Policy applies to our website and our applications. By accessing or using our Service, you acknowledge that you have read, understood, and agreed to the collection, processing, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
 
Clarifications and Definitions
Article One: Definitions
For the purposes of this Privacy Policy:
•	“Applications” refers to all company applications on Android and Apple iOS operating systems.
•	“Account” means the account created for you to access our Service or parts of our Service.
•	“Company” (referred to as “the Company”, “we”, “us”, or “our” in this Agreement) refers to United Sama Company.
•	“Cookies” are small files placed on your computer, mobile device, or any other device by websites, containing details of your usage of the website.
•	“Customer” refers to the person who registers to use the Company’s services.
•	“Device” means any device that can access the Service, such as a computer, mobile phone, or tablet.
•	Internet Protocol Address (IP Address): A number assigned to each device connected to the Internet. IP addresses are usually assigned in geographic blocks and can often be used to identify the geographic location from which a device connects to the Internet.
•	“Personal Data” means any information relating to an identified or identifiable individual.
•	“Service” refers to the Company’s website and applications.
•	“Service Provider” means any natural or legal person who processes data on behalf of the Company, including third parties engaged to facilitate the Service, provide the Service on the Company’s behalf, perform Service-related tasks, or assist in analyzing how the Service is used.
•	“Usage Data” refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
•	“Website” refers to the Company’s website, accessible at: https://samataxi.app
•	“You” means the individual accessing or using the Service, or the company or legal entity on whose behalf such individual is accessing or using the Service, as applicable.
 
Article Two: Collection and Use of Your Personal Data
Types of Data Collected
Personal Data
While using our Service, we may ask you to provide certain personally identifiable information to contacting or identifying you. This may include, but is not limited to:
•	Email address
•	First and last name
•	Phone number
•	Address, country, region, postal code, and city
•	Usage Data
Usage Data
Usage Data is collected automatically when using the Service.
Usage Data may include information, such as your device’s IP address, browser type and version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, device identifiers, and other diagnostic data.
When you access the Service via a mobile device, we may collect certain information automatically, including but not limited to the type of mobile device you use, your mobile device’s unique ID, your mobile device IP address, your mobile operating system, the type of mobile Internet browser you use, device identifiers, and other diagnostic data.
We may also collect information that your browser sends whenever you visit our Service or when you access the Service via a mobile device.
 
Cookies and Tracking Technologies
We use Cookies and similar tracking technologies to track activity on our Service and store certain information. Tracking technologies include beacons, tags, and scripts to collect and track information and to improve and analyze our Service.
Technologies we use may include:
•	Browser Cookies: Cookies are small files placed on your device. You can instruct your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if you do not accept Cookies, you may not be able to use some parts of our Service.
•	Web Beacons: Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, or single-pixel gifs) that allow the Company to count users who have visited pages or opened emails and for other related website statistics.
 
Use of Your Personal Data
The Company may use Personal Data for the following purposes:
•	To provide and maintain our Service, including monitoring usage of our Service.
•	To manage your Account and your registration as a user of the Service.
•	For the performance of a contract, including fulfillment of purchases or other contracts entered into through the Service.
•	To contact you via email, phone calls, SMS, push notifications, or similar electronic communications regarding general, security updates, and service-related communications.
•	To provide you with news, special offers, and general information about services similar to those you have purchased or inquired about, unless you have opted out of receiving such information.
•	To manage and respond to your requests.
•	For business transfers, such as mergers, sales of assets, restructuring, or similar transactions.
•	For other purposes, such as data analysis, identifying usage trends, evaluating promotional campaigns, improving our Service, products, marketing, and your experience.
 
Third-Party Services
We may share personal and non-personal information with third parties, such as advertisers, promotional partners, marketing partners, affiliates, and business partners. We may also transfer such information in connection with mergers, asset sales, or business reorganizations.
We may engage trusted third-party service providers to perform services, such as hosting, server maintenance, database management, email management, payment processing, customer service, and order fulfillment. We may share your information with these providers solely to enable them to perform services on our behalf.
We may share log file data, including IP addresses, for analytics purposes with third parties, such as analytics partners, application developers, and advertising networks. IP addresses may be used to estimate location, connection speed, shared access, and device type. We may also disclose information to government authorities or law enforcement when required by law or necessary to protect rights, safety, or prevent illegal activities.
 
Retention of Your Personal Data
The Company will retain your Personal Data only as long as necessary for the purposes set out in this Privacy Policy, including compliance with legal obligations, dispute resolution, and enforcement of agreements.
Usage Data is generally retained for a shorter period unless required for security or service improvements.
 
Deletion of Your Personal Data
•	You may request deletion of your Personal Data.
•	We will respond to deletion or data transfer requests via email within one month and specify the timeframe for deletion or transfer.
 
Transfer of Your Personal Data
Your information may be processed at the Company’s operating offices and other locations where processing parties are located, including outside your jurisdiction.
By agreeing to this Privacy Policy and submitting your information, you consent to such transfers. The Company will take reasonable steps to ensure adequate data protection safeguards.
 
Disclosure of Your Personal Data
Article Three: Business Transactions
If the Company is involved in a merger, acquisition, or asset sale, your Personal Data may be transferred, with prior notice.
Law Enforcement and Misuse Fees
The Company may disclose your Personal Data if required by law or governmental request. By registering, you agree to the application of misuse or misconduct fees and penalties according to the Company’s internal regulations.
Other Legal Requirements
The Company may disclose Personal Data in good faith to:
•	Comply with legal obligations
•	Protect and defend the Company’s rights or property
•	Prevent or investigate wrongdoing
•	Protect personal safety of users or the public
•	Protect against legal liability
 
Security of Your Personal Data
The security of your Personal Data is important to us; however, no method of transmission or electronic storage can be guaranteed to be 100% secure. We strive to use commercially acceptable means to protect your data but cannot guarantee absolute security.
 
Links to Other Websites
Our Service may contain links to third-party websites not operated by us. We strongly advise reviewing the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content or privacy practices of third-party sites.
 
Changes to This Privacy Policy
We may update this Privacy Policy from time to time. We will notify you by posting the updated Privacy Policy on this page and updating the “Last Updated” date. We may also notify you via email or prominent notice on our Service.
 
Usage and Safety Regulations
When requesting a trip, the following are prohibited:
•	Prohibition of smoking.
•	Intercity passenger transport is strictly prohibited.
•	Seat belt use is mandatory.
•	Prohibition of sharing your personal data; only limited data is displayed to drivers through the application.
•	Passengers are not responsible for traffic violations committed by the driver during the trip.
 
Google Sign-In
We use Google Sign-In to register you in “My Hub” and the “Operator” application. When you sign in through Google, we may receive certain information, such as your name, location, language, profile picture, and email address, in accordance with Google API Services User Data Policy.
 
Apple Pay Integration
If you choose to top up your wallet using Apple Pay, we collect and process certain information required to facilitate the transaction, such as Apple Pay account details and the amount. This data is transferred and managed securely according to Apple’s privacy and security standards. We do not store your payment details or share them with unauthorized third parties. All transactions are subject to Apple’s Privacy Policy and Terms of Service.
 
Contact Us
If you have any questions about this Privacy Policy, you can contact us via:
•	Website: https://samataxi.app
•	Email: support@samataxi.sa
•	Phone: 0509185515`
    },
    terms: {
      title: 'Terms & Conditions',
      intro: 'Terms and Conditions – (Vehicle Dispatch License)',
      sec1Title: '',
      sec1Content: '',
      sec2Title: '',
      sec2Content: '',
      sec3Title: '',
      sec3Content: '',
      fullText: `First: Legal Status of the Company

Company Role
United Sama Company, owner of the Sama Taxi application, operates as a licensed technology platform to perform vehicle dispatch activities in accordance with the regulations and instructions of the Transport Authority in the Kingdom of Saudi Arabia. Its role is limited to directing and organizing transportation requests and connecting customers with registered captains on the platform. The Company is not considered a transportation service provider and is not a party to the transport contract.

Second: Transport Contract and Responsibilities

Transport Contract
The transport contract is concluded directly between the captain and the customer. The captain is responsible for executing the trip, complying with the Transport Authority requirements, and collecting the fare from the customer. The Company bears no responsibility for the execution of the trip or its outcomes.

Third: Non-Payment and Trip Cancellations

No Compensation Obligation
The Company bears no financial obligation to compensate the captain for any unpaid amounts.

Fourth: Complaints and Disputes

Complaint Mechanism
The Company is committed to receiving and reviewing complaints submitted by customers or captains according to its approved procedures. Its role is limited to verification, organization, and taking appropriate administrative or technical measures. No financial obligation or compensation arises from the Company, unless the damage results from a proven technical malfunction of the platform.

Fifth: Captain Status

Captain Independence
The captain acknowledges that they operate as an independent, legally licensed transportation service provider. There is no employment, partnership, or agency relationship with the Company. The captain bears full legal, operational, and financial responsibility resulting from providing the transportation service.

Sixth: Acknowledgment and Consent

Captain Acknowledgment
By using the Sama Taxi application, the captain acknowledges that they have read, understood, and agreed to these terms. The captain understands that the Company’s role is limited to vehicle dispatch and organizing requests, and that the Company is not obligated to compensate for any losses or claims arising from customer actions, in accordance with the laws of the Kingdom of Saudi Arabia.`
    },
    footer: {
      desc: 'Leading the way in digital transportation solutions across Saudi Arabia. Connects you and guides you.',
      copy: 'All rights reserved.'
    }
  },
  ar: {
    nav: {
      main: 'الرئيسية',
      privacy: 'سياسة الخصوصية',
      terms: 'الشروط والأحكام',
      download: 'تحميل التطبيق',
      slogan: 'يوصلك و يهديك'
    },
    hero: {
      badge: 'متوفر الآن في جميع مدن المملكة',
      title: 'ثقة',
      titleHighlight: 'عملائنا',
      titleEnd: 'هي من صنعتنا.',
      desc: 'خدمات نقل متميزة، آمنة وموثوقة بين يديك. اكتشف لماذا سما هي الخيار المفضل للملايين في جميع أنحاء المملكة.',
      btnPrimary: 'احجز رحلة الآن',
      btnSecondary: 'استكشف الخدمات'
    },
    services: {
      title: 'خدماتنا المتخصصة',
      s1: { title: 'توصيل الركاب', desc: 'نقل متميز من نقطة إلى نقطة مع سائقين محترفين.', label: 'توصيل الركاب' },
      s2: { title: 'سائقة سما للبنات', desc: 'سائقات حصريات لراحة وخصوصية ركابنا من الإناث.', label: 'سما للبنات' },
      s3: { title: 'توصيل الطلبات', desc: 'توصيل الطرود والطلبات بشكل موثوق في جميع أنحاء المدينة في دقائق.', label: 'توصيل الطلبات' }
    },
    about: {
      title: 'قصتنا',
      desc: 'من مبادرة محلية في سكاكا إلى رائد وطني في مجال النقل. رحلة سما تاكسي هي شهادة على الجودة والثقة.',
      quote: '"ثقة عملائنا هي من حضرت اسمنا"',
      arabicQuote: 'ثقة عملائنا هي ما يصنعنا.',
      timeline: [
        { year: '2017', event: 'الانطلاق في سكاكا', desc: 'بدأ التطبيق أولى عملياته في مدينة سكاكا.' },
        { year: '2018', event: 'التوسع', desc: 'سما توسع نطاق وصولها لخدمة المزيد من السكان والمسافرين.' },
        { year: '2020', event: 'ملكية جديدة', desc: 'استحواذ استراتيجي لتعزيز الخدمات ونطاق العمليات.' },
        { year: '2021', event: 'توسع كبير', desc: 'الإطلاق في الرياض والمنطقة الشرقية والمنطقة الغربية.' },
        { year: '2022', event: 'النمو', desc: 'تنظيم مكافآت ومسابقات ضخمة لمستخدمينا المخلصين.' },
        { year: '2024', event: 'على مستوى الوطن', desc: 'التوسع لتغطية معظم مدن المملكة بأسطول  2024.' }
      ]
    },
    privacy: {
      title: 'سياسة الخصوصية',
      effective: 'تاريخ التحديث الأخير: 10/02/2026',
      sec1Title: '',
      sec1Content: '',
      safetyTitle: '',
      safetyContent: '',
      sec2Title: '',
      sec2Content: '',
      sec3Title: '',
      sec3Content: '',
      fullText: `تلتزم شركة متحدون سما لخدمات النقل بحماية خصوصيتك، حيث تبيّن سياسة الخصوصية هذه كيف تجمع الشركة معلوماتك الشخصية وكيف تستخدمها وتفصح عنها.
تنطبق سياسة الخصوصية هذه على موقعنا الإلكتروني وكذلك على تطبيقنا. وبمجرد وصولك إلى خدمتنا أو استخدامها فإنك تقرّ بأنك قد قرأت وفهمت ووافقت على جمع ومعالجة معلوماتك الشخصية وتخزينها واستخدامها والإفصاح عنها كما هو موضح في سياسة الخصوصية وشروط الخدمة الخاصة بنا.
التوضيحات والتعريفات
البند الأول : التعريفات
لأغراض سياسة الخصوصية هذه، فإن:
·        يشير مصطلح "التطبيقات" إلى جميع تطبيقات الشركة عبر أنظمة التشغيل أندرويد وأبل «iOS».
·        المقصود بالحساب هو الحساب الذي يتم إنشاؤه لك خصيصا للوصول إلى خدمتنا أو جزء من خدمتنا.
·        يشير مصطلح الشركة (المشار إليها باسم "الشركة" أو "نحن" أو "شركتنا" في هذه الاتفاقية) إلى شركة متحدون سما .
·        "ملفات تعريف الارتباط" هي ملفات صغيرة الحجم تضعها المواقع الإلكترونية على جهازك الحاسوب أو جهازك المحمول أو أي جهاز آخر، وتحتوي هذه الملفات على تفاصيل ومعلومات استخدامك للموقع.
·        يشير وصف "العميل" إلى الشخص الذي يقوم بالتسجيل لاستخدام خدمات الشركة.
·        مصطلح "الجهاز" يعني أي جهاز يمكن من خلاله الوصول إلى الخدمة، مثل جهاز الحاسوب أو الهاتف المحمول أو الجهاز اللوحي.
·        عنوان بروتوكول الإنترنت (عنوان IP): يتم تعيين أرقام لكل جهاز متصل بالإنترنت، وتعرف هذه الأرقام بعنوان بروتوكول الإنترنت (IP)، وعادة ما يتم تعيين هذه الأرقام في مجموعات جغرافية، كما يمكن استخدام عنوان (IP) غالبا لتحديد الموقع الجغرافي الذي يتصل منه الجهاز بالإنترنت.
·        يقصد بالبيانات الشخصية أي معلومات تتعلق بفرد محدد أو يمكن تحديده.
·        تشير الخدمة إلى الموقع الإلكتروني والتطبيقات الخاصة بالشركة.
·        مزود الخدمة هو أي شخص طبيعي أو اعتباري يعمل على معالجة البيانات بالنيابة عن الشركة، حيث يشير المصطلح إلى الشركات أو الأفراد التابعين لجهات خارجية تم توظيفهم من قِبَل الشركة لتيسير تقديم الخدمة أو لتقديم الخدمة نيابة عن الشركة أو لأداء الخدمات الجانبية المتعلقة بالخدمة أو لمساعدة الشركة في تحليل كيفية استخدام الخدمة.
·        "بيانات الاستخدام" هي البيانات التي يتم جمعها تلقائياً، وتنتج هذه البيانات إما من خلال استخدام الخدمة أو من البنية التحتية للخدمة نفسها (على سبيل المثال، مدة زيارة الصفحة عبر الموقع الإلكتروني)
·        يشير "الموقع الإلكتروني" إلى الموقع الإلكتروني للشركة، ويمكن الوصول إليه من خلال «  https://samataxi.app».
·        يشير الضمير "أنت" أو صيغة المخاطب إلى الفرد الذي يصل إلى الخدمة أو يستخدمها، أو الشركة أو الكيان القانوني الذي من خلاله يصل الفرد إلى الخدمة أو يستخدمها بالنيابة عنه حسب الاقتضاء.
البند الثاني : جمع بياناتك الشخصية واستخدامها
أنواع البيانات التي يتم جمعها:
البيانات الشخصية
قد نطلب منك أثناء استخدام خدمتنا تزويدنا بمعلومات شخصية معينة لاستخدامها للاتصال بك أو التعرف عليك، قد تتضمن معلومات التعريف الشخصية على سبيل المثال لا الحصر:
·        عنوان البريد الإلكتروني
·        الاسم الأول واسم العائلة
·        رقم الهاتف
·        العنوان، الدولة، المحافظة، الرمز البريدي، المدينة
·        بيانات الاستخدام
بيانات الاستخدام
يتم جمع بيانات الاستخدام بشكل تلقائي عند استخدام الخدمة.
قد تشمل بيانات الاستخدام على معلومات مثل عنوان بروتوكول الإنترنت لجهازك (مثل عنوان IP) ونوع المتصفح وإصدار المتصفح وصفحات الخدمة أو المواقع التي تزورها ووقت وتاريخ زيارتك والمدة التي تقضيها على تلك الصفحات، وكذلك معرفات الجهاز المستخدم والبيانات التشخيصية الأخرى.
يجوز لنا جمع معلومات معينة تلقائياً عندما تستخدم أو تصل إلى الخدمة من خلال جهاز المحمول، وتشمل المعلومات على سبيل المثال لا الحصر على نوع الجهاز المحمول الذي تستخدمه ورمز المعرف الفريد لجهازك المحمول، بالإضافة إلى عنوان بروتوكول الإنترنت (IP) الخاص بجهازك المحمول، وتشمل المعلومات ايضا على نظام تشغيل الهاتف المحمول ونوع متصفح الإنترنت على الهاتف المحمول الذي تستخدمه ومعرّفات الجهاز والبيانات التشخيصية الأخرى.
قد نجمع ايضا المعلومات التي يرسلها متصفحك عندما تزور خدمتنا أو عندما تصل إلى الخدمة من خلال الجهاز المحمول.
ملفات تعريف الارتباط وتقنيات التتبع
نستخدم ملفات تعريف الارتباط وتقنيات التتبع المماثلة لتتبع الأنشطة على خدمتنا ولتخزين معلومات معينة، وتشمل تقنيات التتبع المستخدمة على إشارات الويب وعلامات تتبع الويب والبرامج النصية لجمع المعلومات وتتبعها ولتحسين خدمتنا وتحليلها، كما قد تشمل التقنيات التي نستخدمها على:
·        ملفات تعريف الارتباط الخاصة بالمتصفح: ملف تعريف الارتباط هو ملف صغير يوضع على جهازك، يمكنك رفض جميع ملفات تعريف الارتباط أو تحديد متى يتم إرسال ملف تعريف الارتباط، ولكن في حال رفضت ملفات تعريف الارتباط فقد لا تتمكن من استخدام بعض الأجزاء من خدمتنا. تستخدم خدمتنا ملفات تعريف الارتباط ما لم تقم بتعديل إعدادات المتصفح بحيث يرفضها.
·        إشارات الويب: قد تحتوي أقسام معينة من خدمتنا ورسائل البريد الإلكتروني الخاصة بنا على ملفات إلكترونية صغيرة تُعرف باسم إشارات الويب (تسمى ايضا باسم جيفس أو علامات البكسل أو جيفس أحادية البكسل) والتي تسمح للشركة بإحصاء المستخدمين الذين زاروا تلك الصفحات أو فتح بريداً إلكترونياً معيناً ولجمع إحصائيات مواقع الويب الأخرى ذات الصلة (على سبيل المثال، تسجيل مدى تردد الزوار على قسم معين والتحقق من سلامة النظام والخادم).
استخدام بياناتك الشخصية
يجوز للشركة استخدام بياناتك الشخصية للأغراض التالية:
·        تقديم خدمتنا والمحافظة عليها، بما في ذلك مراقبة استخدام خدمتنا.
·        إدارة حسابك: لإدارة تسجيلك كمستخدم للخدمة، حيث يمكن أن تمنحك البيانات الشخصية التي تقدمها لنا إمكانية الوصول إلى المزايا المختلفة للخدمة المتاحة لك كمستخدم مسجل.
·        إبراء الذمة من خلال العقد: الامتثال والتعهد بعقد الشراء للخدمات التي اشتريتها أو بأي عقد آخر من خلال الخدمة.
·        التواصل معك: للاتصال بك عن طريق البريد الإلكتروني أو المكالمات الهاتفية أو الرسائل النصية القصيرة أو غير ذلك من أشكال الاتصالات الإلكترونية المماثلة مثل الإشعارات الفورية لتطبيقات الهاتف المحمول حول التحديثات أو الاتصالات الإعلامية المتعلقة بالوظائف أو المنتجات أو الخدمات المتعاقد عليها، بما في ذلك التحديثات الأمنية، وذلك عند الضرورة أو الحاجة إليها.
·        تزويدك بالأخبار والعروض والمعلومات العامة حول السلع والخدمات والأحداث الأخرى التي نقدمها ذات العلاقة بالخدمات التي اشتريتها مسبقاً أو استفسرت عنها ما لم تكن قد اخترت عدم تلقي هذه المعلومات.
·        إدارة طلباتك: لتنفيذ وإدارة طلباتك.
·        عمليات النقل التجارية: قد نستخدم معلوماتك لتقييم أو دمج أو تجريد أو إعادة هيكلة أو إعادة تنظيم أو حل أو بيع أو نقل لبعض أو كل أصولنا، سواء كان ذلك بسبب مخاوف مستمرة أو كجزء من الإفلاس أو التصفية أو إجراءات مماثلة، كما تعتبر البيانات الشخصية التي نحتفظ بها عن مستخدمي الخدمة من بين الأصول المنقولة.
·        أسباب أخرى: قد نستخدم معلوماتك لأغراض أخرى، مثل تحليل البيانات وتحديد الاستخدامات الشائعة وتحديد فعالية حملاتنا الترويجية ولتقييم وتحسين موقعنا وتطبيقنا ومنتجاتنا وخدماتنا وتسويقنا، وكذلك تحسين تجربتك.
خدمات الطرف الثالث
يحق لنا أن نشارك المعلومات الشخصية وغير الشخصية التي نجمعها مع أطراف ثالثة مثل المعلنين ورعاة المسابقات وشركاء الترويج والتسويق وغيرهم ممن يقدمون المحتوى الخاص بنا أو الذين نعتقد أن منتجاتهم أو خدماتهم قد تهمك، كما يجوز لنا ايضا مشاركتها مع شركاتنا التابعة الحالية والمستقبلية وشركاء الأعمال، وقد نشارك معلوماتك الشخصية وغير الشخصية أو ننقلها إلى حلفائنا في المصلحة إذا كنا مشاركين في عملية اندماج أو بيع أصول أو إعادة تنظيم أعمال أخرى.
قد نقوم بإشراك موفري خدمات الطرف الثالث الموثوق بهم لأداء الوظائف وتقديم الخدمات، مثل استضافة وصيانة خوادمنا وتطبيق الهاتف وتخزين وإدارة قاعدة البيانات وإدارة البريد الإلكتروني والتخزين ومعالجة بطاقات الائتمان وخدمة العملاء وتنفيذ الطلبات للمنتجات والخدمات التي قد تشتريها من خلال التطبيق، ومن المحتمل أن نشارك معلوماتك الشخصية وغير الشخصية مع هذه الأطراف الثالثة لتمكينهم من أداء هذه الخدمات لنا ولكم.
يجوز لنا مشاركة أجزاء من ملفات السجل، بما في ذلك عناوين بروتوكول الانترنت (IP)، لأغراض التحليلات مع أطراف ثالثة مثل شركاء تحليلات الويب ومطوري التطبيقات والشبكات الإعلانية، ويمكن استخدام عنوان بروتوكول الانترنت (IP) الخاص بك لتقدير الموقع الجغرافي والتقنيات الأخرى مثل سرعة الاتصال وما إذا كنت قد زرت التطبيق في موقع مشترك، وكذلك نوع الجهاز المستخدم لزيارة التطبيق. قد يقومون بتجميع معلومات حول إعلاناتنا وما تراه على التطبيق ثم تقديم التدقيق والبحث وإعداد التقارير لنا وللمعلنين لدينا. وقد نكشف ايضا عن معلومات شخصية وغير شخصية عنك إلى الحكومة أو مسؤولي إنفاذ القانون أو الأطراف الخاصة لأننا نعتقد أنها ضرورية أو مناسبة للرد على المطالبات والإجراءات القانونية (بما في ذلك مذكرات الاستدعاء) لحماية الحقوق والمصالح أو تلك الخاصة بطرف خارجي، أو سلامة الجمهور أو أي شخص، وذلك لمنع أو إيقاف أي نشاط غير قانوني أو غير أخلاقي أو نشاط قابل للتنفيذ من الناحية القانونية، أو للامتثال لأوامر المحكمة والقوانين والقواعد واللوائح المعمول بها.
الاحتفاظ ببياناتك الشخصية
ستحتفظ الشركة ببياناتك الشخصية فقط طالما كان ذلك ضرورياً للأغراض المنصوص عليها في سياسة الخصوصية هذه، بحيث سنحتفظ ببياناتك الشخصية ونستخدمها بالقدر اللازم للامتثال لالتزاماتنا القانونية (على سبيل المثال، إذا كنا مطالبين بالاحتفاظ ببياناتك للامتثال للقوانين المعمول بها) وحل النزاعات وإنفاذ اتفاقياتنا وسياساتنا القانونية.
ستحتفظ الشركة ايضا ببيانات الاستخدام لأغراض التحليل الداخلي، بحيث يتم الاحتفاظ ببيانات الاستخدام عموماً لفترة زمنية قصيرة، ولكن نحن ملزمون قانوناً بالاحتفاظ بهذه البيانات لفترات زمنية أطول في حالة استخدام هذه البيانات لتعزيز الأمان أو لتحسين وظائف خدمتنا.
حذف بياناتك الشخصية
·        يمكن حذف بياناتك الشخصية عند الطلب.
·        نرد على طلب الحذف ونقل البيانات الشخصية المقدمة عن طريق البريد الإلكتروني خلال شهر، ونحدد فترة حذف البيانات ونقلها.
نقل بياناتك الشخصية
تتم معالجة معلوماتك وبياناتك الشخصية في مكاتب تشغيل الشركة وفي مكان تواجد الأطراف المشاركة في المعالجة، وهذا يعني أنه قد يتم نقل هذه المعلومات إلى أجهزة الحاسوب الموجودة خارج ولايتك أو مقاطعتك أو بلدك أو الولاية القضائية الحكومية التي قد تختلف فيها قوانين حماية البيانات عن تلك الموجودة في ولايتك القضائية.
عند موافقتك على سياسة الخصوصية هذه وعند تقديمك للمثل هذه المعلومات فإنك توافق على هذا النقل.
ستتخذ الشركة جميع الخطوات اللازمة بشكل معقول لضمان التعامل مع بياناتك بشكل آمن بما يتوافق مع سياسة الخصوصية هذه، ولن يتم نقل بياناتك الشخصية إلى أي منظمة أو دولة ما لم تكن هناك ضوابط كافية بما في ذلك أمن بياناتك ومعلوماتك الشخصية الأخرى.
الإفصاح عن بياناتك الشخصية
البند الثالث : المعاملات التجارية
إذا كانت الشركة مشاركة في عملية دمج أو استحواذ أو بيع أصول، فقد يتم نقل بياناتك الشخصية، وسنقدم إشعاراً قبل نقل بياناتك الشخصية وإخضاعها لسياسة خصوصية مختلفة.
تطبيق القانون و رسوم اساءة الإستخدام
قد يُطلب من الشركة في ظل ظروف معينة الكشف عن بياناتك الشخصية إذا طُلب منها ذلك بموجب القانون أو استجابة لطلبات من قبل السلطات العامة (على سبيل المثال، محكمة أو وكالة حكومية).
بمجرد تسجيلك معنا ، فإنك توافق على ان الشركة ستقوم بتطبيق الشروط والاحكام الخاصة والعامة في رسوم اساءة الاستخدام او السلوك مع العملاء وذلك قد يعرضك الى بعض العقوبات والرسوم لقاء تلك التجاوزات حسب اللوائح والانظمة الداخلية للشركة .
المتطلبات القانونية الأخرى
قد تفصح الشركة عن بياناتك الشخصية بحسن نية اعتقاداً بوجود ضرورة من أجل:
·        الامتثال لالتزام قانوني
·        حماية حقوق أو ممتلكات الشركة والدفاع عنها
·        منع أي مخالفات محتملة تتعلق بالخدمة والتحقيق فيها
·        حماية السلامة الشخصية لمستخدمي الخدمة أو الجمهور
·        الحماية من المسؤولية القانونية
أمن بياناتك الشخصية
يعد أمان بياناتك الشخصية أمراً في غاية الاهمية بالنسبة لنا، ولكن تذكر أنه لا توجد وسيلة نقل عبر الإنترنت أو طريقة تخزين إلكتروني آمنة بنسبة 100%، نحن نسعى جاهدين لاستخدام وسائل مقبولة تجارياً لحماية بياناتك الشخصية، ولكن لا يمكننا ضمان أمنها المطلق.
الروابط لمواقع إلكترونية أخرى
قد تحتوي خدمتنا على روابط لمواقع أخرى لا سلطة لدينا عليها، وإذا نقرت على رابط لموقع جهة خارجية، فسيتم توجيهك إلى موقع الطرف الثالث، ننصحك بشدة مراجعة سياسة الخصوصية لكل موقع تزوره. ليس لدينا أي سيطرة ولا نتحمل أي مسؤولية عن المحتوى أو سياسات الخصوصية أو ممارسات أي مواقع أو خدمات خاصة بطرف ثالث.
التغييرات على سياسة الخصوصية
قد نقوم بتحديث سياسة الخصوصية الخاصة بنا من وقت لآخر، وسنخطرك بأي تغييرات عن طريق نشر سياسة الخصوصية الجديدة على هذه الصفحة. سنخبرك عبر البريد الإلكتروني و/أو عبر إشعاراً بارزاً على خدمتنا (موقعنا أو تطبيقنا) قبل أن يصبح التغيير سارياً، وكذلك تحديث تاريخ "آخر تحديث" في الجزء العلوي من سياسة الخصوصية هذه.
يُنصح بمراجعة سياسة الخصوصية هذه بشكل دوري لمعرفة أي تغييرات، كما تسري التغييرات التي تطرأ على سياسة الخصوصية هذه عند نشرها على هذه الصفحة.
اللوائح وأنظمة الإستخدام والسلامة : 
عند طلب الرحلة يمنع حسب اللوائح والأنظمة التالي : 
·        يمنع التدخين منعا باتا . 
·        يمنع منعاً باتاً نقل الركاب بين المدن . 
·        الالتزام باستخدام حزام الأمان . 
·        عدم مشاركة بياناتك الشخصية ، حيث يتم عرض الحد الأعلى من البيانات للسائق من خلال التطبيق فقط .
·        لا يتحمل الراكب قيمة أي مخالفات مرورية تتم على السائق أثناء الرحلة . 
تسجيل الدخول عبر جوجل
نستخدم بيانات تسجيل الدخول عبر جوجل لتسجيلك في «My Hub» وتطبيق «Operator»، وعندما تقوم بالتسجيل من خلال جوجل فإننا نتلقى معلومات معينة عنك حسب ما ينطبق على طريقة التسجيل الخاصة بك، وقد تتضمن هذه المعلومات اسمك وموقعك الجغرافي ولغتك وصورة ملفك الشخصي وبريدك الإلكتروني. نحن نلتزم بسياسة بيانات المستخدم الخاصة بسياسة خدمات واجهة برمجة تطبيقات جوجل.
الربط والتكامل مع أبل باي - Apple Pay
إذا اخترت شحن محفظتك باستخدام Apple Pay ، فسنقوم بجمع ومعالجة بعض المعلومات المطلوبة لتسهيل المعاملة، مثل تفاصيل حساب Apple Pay والمبلغ المراد إضافته. يتم نقل هذه البيانات وإدارتها بشكل آمن وفقًا لمعايير الخصوصية والأمان الخاصة بشركة أبل . لا نخزن معلومات الدفع الخاصة بك أو نشاركها مع أطراف ثالثة غير مصرح لها. تخضع جميع المعاملات لسياسة الخصوصية وشروط الخدمة الخاصة بشركة أبل . : 
التواصل معنا
إذا كانت لديك أي أسئلة حول سياسة الخصوصية هذه، يمكنك الاتصال بنا عبر:
·        زيارة موقعنا الإلكتروني: https://samataxi.app
·        البريد الإلكتروني: support@samataxi.sa
·        هاتف: 0509185515`
    },
    terms: {
      title: 'الشروط والأحكام',
      intro: 'شروط وأحكام – (ترخيص توجيه مركبات)',
      sec1Title: '',
      sec1Content: '',
      sec2Title: '',
      sec2Content: '',
      sec3Title: '',
      sec3Content: '',
      fullText: `أولًا: الصفة النظامية للشركة
دور الشركة
تعمل شركة متحدون سما، المالكة لتطبيق سما تكسي، كمنصة تقنية مرخصة لممارسة نشاط توجيه المركبات وفق أنظمة وتعليمات هيئة النقل في المملكة العربية السعودية، ويقتصر دورها على توجيه وتنظيم طلبات النقل وربط العملاء بالكباتن المسجلين في المنصة، ولا تُعد الشركة مقدم خدمة نقل، ولا طرفًا في عقد النقل.

ثانيًا: عقد النقل والمسؤوليات
عقد النقل
يتم إبرام عقد النقل مباشرة بين الكابتن والعميل، ويكون الكابتن هو المسؤول عن تنفيذ الرحلة والالتزام بمتطلبات هيئة النقل وتحصيل الأجرة من العميل، ولا تتحمل الشركة أي مسؤولية عن تنفيذ الرحلة أو نتائجها.

ثالثًا: عدم الدفع وإلغاء الرحلات
عدم الالتزام بالتعويض
لا تتحمل الشركة أي التزام مالي بتعويض الكابتن عن أي مبالغ غير مدفوعة

رابعًا: الشكاوى والنزاعات
آلية الشكاوى
تلتزم الشركة باستقبال ودراسة الشكاوى المقدمة من العملاء أو الكباتن وفق الآليات المعتمدة لديها، ويقتصر دورها على التحقق والتنظيم واتخاذ الإجراءات الإدارية أو التقنية المناسبة، دون أن يترتب على ذلك أي التزام مالي أو تعويض من قبل الشركة، ما لم يكن الضرر ناتجًا عن خلل تقني ثابت يعود للمنصة.

خامسًا: صفة الكابتن
استقلالية الكابتن
يقر الكابتن بأنه يعمل كمقدم خدمة نقل مستقل ومرخص له نظامًا، ولا تربطه بالشركة أي علاقة عمل أو توظيف أو شراكة أو وكالة، ويتحمل الكابتن كامل المسؤولية النظامية والتشغيلية والمالية الناتجة عن تقديم خدمة النقل.

سادسًا: الإقرار والموافقة
إقرار الكابتن
باستخدام الكابتن لتطبيق سما تكسي، فإنه يقر باطلاعه على هذه الشروط وفهمها وموافقته عليها، ويقر بعلمه بأن دور الشركة يقتصر على توجيه المركبات وتنظيم الطلبات فقط، وأنها غير ملزمة بتعويضه عن أي خسائر أو مطالبات ناتجة عن تصرفات العملاء، وذلك وفقًا للأنظمة المعمول بها في المملكة العربية السعودية`
    },
    footer: {
      desc: 'الرائد في حلول النقل الرقمي في جميع أنحاء المملكة العربية السعودية. يوصلك ويهديك.',
      copy: 'جميع الحقوق محفوظة.'
    }
  }
};
